# Generated by Django 6.0.7 on 2026-07-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="allowed_radius_km",
            field=models.FloatField(
                default=1.0,
                help_text="Maximum distance in kilometers allowed for clock-in",
            ),
        ),
    ]
