# Generated by Django 6.0.7 on 2026-07-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_systemsettings_allowed_radius_km"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="shift_end_time",
            field=models.TimeField(blank=True, help_text="e.g., 17:00:00", null=True),
        ),
    ]
